### ISSUE TITLE
悲报小提议

### ISSUE THREAD

**Issue by 502milk** [ifrvn/cecilia#1]
悲报可以用黑白的么，这负片效果有点阴间啊XD

**Comment by ifrvn** [comment]
啊这，我专门做的赛博包浆处理的说，感觉会悲一点（

纯黑白的话你觉得哪个好？

![image](https://user-images.githubusercontent.com/21982381/233851212-bcfad363-ba27-4712-a7ad-1c0ef6f58e59.png)

**Comment by 502milk** [comment]
好像。。。没看出啥区别XD

**Comment by ifrvn** [comment]
左边就是简单拉了黑白；右边加了噪点和浮雕效果，就是现在用的拉成黑白，似乎有种老式电视机的美？

**Comment by 502milk** [comment]
那个都行.jpg~~黑白就行了~~
