### ISSUE TITLE
文字显示出现问题

### ISSUE THREAD

**Issue by Apricityx** [ifrvn/cecilia#10]
![image](https://github.com/ifrvn/cecilia/assets/78242039/d84d84df-90ff-41d5-b5ad-9ccad078449d)
如图
调用命令后后台无报错
CSS用gitee源和自定义源都无法正常显示
插件版本为1.3.0

**Comment by ifrvn** [comment]
![image](https://github.com/ifrvn/cecilia/assets/21982381/5c8ee2d2-0344-486d-bfac-6cecadb9f5e1)

我这没问题，无法复现，请检查你的网络。理论上只要网络通畅就没问题。

看下你的运行环境能否打开这个地址 https://gitee.com/ifrank/harmonyos-fonts/raw/main/css/harmonyos_sans_sc.css

**Comment by Apricityx** [comment]
CSS能正常拉取，我发现Puppeteer插件在加载的时候报错如下，是否和这个有关系
![image](https://github.com/ifrvn/cecilia/assets/78242039/e5097e29-4e20-4278-b6de-7b0eba664c56)

**Comment by ifrvn** [comment]
pptr是什么版本？更新一下或者（已经是最新版的话）删除yarn.lock文件重新yarn一下看看？

**Comment by Apricityx** [comment]
> pptr是什么版本？更新一下或者（已经是最新版的话）删除yarn.lock文件重新yarn一下看看？

已尝试，仍未解决，现已更换docker部署
