### ISSUE TITLE
[koishi v4.17.2] 无法生成喜报悲报图片

### ISSUE THREAD

**Issue by Container-Zero** [ifrvn/cecilia#11]
koishi版本：`4.17.2`(其它依赖保持最新)

插件列表的状态灯为黄灯
![image](https://github.com/ifrvn/cecilia/assets/20435019/259aead1-e126-403a-8ec1-30e776bdf816)

调用`悲报喜报`不显示内容，且后台无报错，无加载失败相关信息

**Comment by Container-Zero** [comment]
插件为最新版本，在上述环境下，喜报插件从停止到启动时，该插件顶部会一闪而过一个警告提示：

![image](https://github.com/ifrvn/cecilia/assets/20435019/9ce67ba6-0ce8-434a-a9a5-9e1b1784836a)

**Comment by ifrvn** [comment]
我的开发环境下没有发现问题。如果你的配置文件koishi.yml里没有问题，要不删掉yarn.lock再重新yarn一下？

![image](https://github.com/ifrvn/cecilia/assets/21982381/ce12ba8b-a012-4871-b781-67d23ffef97a)
