### ISSUE TITLE
悲报：XSS攻击

### ISSUE THREAD

**Issue by XNORIGC** [ifrvn/cecilia#12]
喜报插件可以被XSS注入
例子：
![Image_1720264930413](https://github.com/ifrvn/cecilia/assets/162976879/3dc78252-6826-408a-a669-8a30f1677511)
解决办法：
![Image_1720264936927](https://github.com/ifrvn/cecilia/assets/162976879/f276e278-94ba-4c86-8685-975bdcce75a0)

**Comment by ifrvn** [comment]
感谢反馈，已发布 1.3.1
