### ISSUE TITLE
安卓端koishi问题

### ISSUE THREAD

**Issue by TatleCat** [ifrvn/cecilia#2]
好像不能用a
没有显示具体指令
或者我该怎么使用(0.o?)
![Screenshot_20230425_062621](https://user-images.githubusercontent.com/128877938/234130052-22049526-714e-4097-a0a8-a76c5199d6a7.jpg)

**Comment by ifrvn** [comment]
看日志是不是puppeteer炸了，这个不是插件的问题。

**Comment by TatleCat** [comment]
并没有,其他插件都正常
你试下安卓koishi (?

**Comment by ifrvn** [comment]
至少我这安卓上pptr是炸的，然后就像你截图的那样插件启用了但是没有指令。

![Screenshot_2023-04-25-20-06-08-26_ba821e0d3dada72](https://user-images.githubusercontent.com/21982381/234271236-f313d57a-6d71-45e5-8244-e87328033aca.jpg)

**Comment by ifrvn** [comment]
然后，如果你不能提供有效日志，那么我也没别的办法判断问题，只能恕不再回复了。

![RZR0ZDJG(G4`XVT7UA31C0L](https://user-images.githubusercontent.com/21982381/234272132-9b08aa3d-7a18-41b7-9d46-8b991d344bbd.jpg)

**Comment by ifrvn** [comment]
根据 https://github.com/koishijs/koishi-android/issues/10#issuecomment-1537055890

> 尝试在控制台 puppeteer 插件的配置项中配置 --no-sandbox 参数

这或许可以解决问题
