### ISSUE TITLE
喜报和悲报的字体有点怪怪的

### ISSUE THREAD

**Issue by yi03** [ifrvn/cecilia#3]
![图片1](https://github.com/ifrvn/cecilia/assets/32034998/0209b448-c1f5-4e8f-bbef-06c734f860ca)
喜报如果是字母或数字的话，很多线都特别细，看起来怪怪的。比如UVWXY这几个字母。希望能换个字体。
谢谢大佬。

**Comment by ifrvn** [comment]
已增加字体配置项，默认使用[思源黑体](https://github.com/adobe-fonts/source-han-sans/blob/master/README-CN.md)，显示效果应该会好一些，不过要自己在koishi运行的系统上安装字体。

**Comment by yi03** [comment]
> 已增加字体配置项，默认使用[思源黑体](https://github.com/adobe-fonts/source-han-sans/blob/master/README-CN.md)，显示效果应该会好一些，不过要自己在koishi运行的系统上安装字体。

好的，谢谢大佬！

**Comment by ifrvn** [comment]
默认换成 [Noto Sans SC](https://fonts.google.com/noto/specimen/Noto+Sans+SC) 了，和思源黑体是一样的字体，但是可以直接用 Google 的 cdn 引用，也就是不需要手动装字体了。
