### ISSUE TITLE
喜报和悲报文字渲染好像有问题

### ISSUE THREAD

**Issue by Mulsd** [ifrvn/cecilia#6]
![`GDE9W~M4@VQBAHV$ED7}NL](https://github.com/ifrvn/cecilia/assets/49836364/aff201ef-b858-410e-9bbd-60feaa8c9206)

**Comment by ifrvn** [comment]
不知道谷歌这`Noto Sans SC`字体咋回事，之前还是好的。换鸿蒙算了
