### ISSUE TITLE
喜报在沙盒中使用会莫名在内容结尾处带上 `html>`

### ISSUE THREAD

**Issue by ifrvn** [ifrvn/cecilia#7]
大概是沙盒限定，实际使用没什么影响吧？有空再看看

![image](https://github.com/ifrvn/cecilia/assets/21982381/82c7bed4-9b5c-44c1-9110-d10ab165e53b)

**Comment by ljyearnl** [comment]
悲报 有影响
这是在QQ里
![image](https://github.com/ifrvn/cecilia/assets/33179879/d8251322-8143-48a4-bd30-e91535a144c8)

**Comment by ljyearnl** [comment]
喜报
`function html`里面的最开始的`<html>`和最后的`</html>`删了就好了

**Comment by ifrvn** [comment]
@ljyearnl 好的，删掉惹。感谢反馈！
