### ISSUE TITLE
[koishi v4.14.2] 无法生成喜报悲报图片

### ISSUE THREAD

**Issue by BSTluo** [ifrvn/cecilia#9]
koishi版本：
4.14.2

puppeteer版本：
3.5.0

报错内容：
无法生成图片

报错日志详情：
![image](https://github.com/ifrvn/cecilia/assets/36332288/8038a0b7-21eb-4a98-a6ce-4477db203fdf)

**Comment by ifrvn** [comment]
更新下喜报版本？之前css的CDN用的JsDelivr，国内访问不太好，1.2.2换成ghproxy了。   https://github.com/ifrvn/cecilia/issues/8 

如果更新过了，看下喜报的配置里 高级配置 importCSS 项是不是 ghproxy 的链接，不是的话恢复默认值保存即可。

![image](https://github.com/ifrvn/cecilia/assets/21982381/76a52043-688b-4037-a877-20a3ccd4ee81)

**Comment by BSTluo** [comment]
好耶成功了！
